Add jemalloc by default(3/5)
DerpFest-AOSP/bionic pull request #3
Opened 2024-03-14 09:18 UTC by MxkulSharma

Jemalloc by default is good because of  : 

1. Reduced Fragmentation: jemalloc employs sophisticated algorithms to allocate memory in a way that minimizes fragmentation. This fragmentation occurs when freed memory becomes scattered in small chunks, making it difficult to allocate larger blocks efficiently. jemalloc's approach helps maintain contiguous memory regions, leading to faster allocation and deallocation operations.

2. jemalloc excels in multi-threaded environments. It utilizes thread-caching mechanisms and per-thread allocation arenas to minimize contention and improve memory access speed for concurrent threads.

3. jemalloc provides valuable debugging features that can aid in troubleshooting memory-related issues within the operating system. These tools can help pinpoint memory leaks, identify memory usage patterns, and diagnose allocation/deallocation problems, leading to a more stable and reliable system.

4. It also make's the device perform well at higer  load's and improve performance. 

You can check other PR regarding this from these Links.  

[Build](https://github.com/DerpFest-AOSP/build/pull/14) (1/5)
[Build_soong](https://github.com/DerpFest-AOSP/build_soong/pull/6) (2/5)
[Bionic](https://github.com/DerpFest-AOSP/bionic/pull/3) (3/5)
[external_jemalloc_new](https://github.com/DerpFest-AOSP/external_jemalloc_new/pull/1) (4/5)
[manifest](https://github.com/DerpFest-AOSP/manifest/pulls/21) (5/5)
[System_core](https://github.com/DerpFest-AOSP/system_core/pull/5)

2024-03-14 13:58 UTC, NurKeinNeid requested changes
Please drop unrelated commits first and you're missing system/core.

2024-03-15 17:08 UTC, MxkulSharma commented
> Please drop unrelated commits first and you're missing system/core.


Sure thank you for the feedback, i have droped all the unrelated commits and i can't find the missing commit of system/core.
Thank you.

2024-03-15 21:15 UTC, NurKeinNeid requested changes
Weren't you wondering where 4/4 was? You should also always look at the original author at first. It originally comes from AOSPA.

https://gerrit.aospa.co/c/AOSPA/android_system_core/+/30308

2024-03-16 03:01 UTC, MxkulSharma commented
> Weren't you wondering where 4/4 was? You should also always look at the original author at first. It originally comes from AOSPA.
> 
> https://gerrit.aospa.co/c/AOSPA/android_system_core/+/30308



> Weren't you wondering where 4/4 was? You should also always look at the original author at first. It originally comes from AOSPA.
> 
> https://gerrit.aospa.co/c/AOSPA/android_system_core/+/30308

i am sorry i assumed external_jemalloc as the last commit for it. 

I wasn't aware of the origin author, If you want i can force push all commit's and make change's with the origin author.

2024-03-17 10:11 UTC, NurKeinNeid requested changes
I don't understand why you force pushed it and changed authorship. I didn't mention that at all. Everything was fine, now it's wrong.

2024-03-17 10:32 UTC, MxkulSharma commented
> I don't understand why you force pushed it and changed authorship. I didn't mention that at all. Everything was fine, now it's wrong.

I will make it right now. Thank you.

2024-03-17 14:21 UTC, NurKeinNeid approved these changes
Thanks for your contribution. Looks good to me now but Pixels don't like these changes. I need to add the changed repos to be excluded in pixel branch manifest. But next weekend's I will be very busy with QPR2.

2024-03-17 15:03 UTC, MxkulSharma commented
> Thanks for your contribution. Looks good to me now but Pixels don't like these changes. I need to add the changed repos to be excluded in pixel branch manifest. But next weekend's I will be very busy with QPR2.

ok no problem so should i keep these pr open or should i close them or do i need to  exclude these repo from pixel branch?

2024-03-17 15:17 UTC, NurKeinNeid commented
Just keep the pull requests open. I have a lot of local uncommited changes because of qpr2 and cant tell yet if I will merge to qpr1  or qpr2 only and when I will find time.

2024-03-23 13:15 UTC, merged

2024-03-23 13:28 UTC, NurKeinNeid commented
Still no system/core commit